export const INITIALIZE = '@libs/dashboard/INITIALIZE'
export const INITIALIZE_SUCCESS = '@libs/dashboard/INITIALIZE_SUCCESS'
export const INITIALIZE_FAILURE = '@libs/dashboard/INITIALIZE_FAILURE'

export const FETCH_DASHBOARD_DATA = '@libs/dashboard/FETCH_DASHBOARD_DATA'
export const FETCH_DASHBOARD_DATA_SUCCESS = '@libs/dashboard/FETCH_DASHBOARD_DATA_SUCCESS'
export const FETCH_DASHBOARD_DATA_FAILURE = '@libs/dashboard/FETCH_DASHBOARD_DATA_FAILURE'

export const FETCH_DASHBOARD_METADATA_DATA = '@libs/dashboard/FETCH_DASHBOARD_METADATA_DATA'
export const FETCH_DASHBOARD_METADATA_DATA_SUCCESS = '@libs/dashboard/FETCH_DASHBOARD_METADATA_DATA_SUCCESS'
export const FETCH_DASHBOARD_METADATA_DATA_FAILURE = '@libs/dashboard/FETCH_DASHBOARD_METADATA_DATA_FAILURE'

export const FILTER_DASHBOARD_TIMESTAMP = '@libs/dashboard/FILTER_DASHBOARD_TIMESTAMP'
export const FILTER_DASHBOARD_TIMESTAMP_SUCCESS = '@libs/dashboard/FILTER_DASHBOARD_TIMESTAMP_SUCCESS'
export const FILTER_DASHBOARD_TIMESTAMP_FAILURE = '@libs/dashboard/FILTER_DASHBOARD_TIMESTAMP_FAILURE'
